project_id = "doulsumepjfihqowzheq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54324
max_connections = 100
max_channels_per_client = 100
max_joins_per_second = 100
max_events_per_second = 100

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.hubspot-validate]
verify_jwt = false

[functions.hubspot-sync]
verify_jwt = false